import unittest

from python.src.y2025.dec07 import Dec07


class TestDec07(unittest.TestCase):
    data = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".splitlines()

    def test_part_1(self):
        self.assertEqual(21, Dec07(instructions=self.data).part_1())

    def test_part_2(self):
        self.assertEqual(0, Dec07(instructions=self.data).part_2())


if __name__ == '__main__':
    unittest.main()
